#!/bin/bash

for word in $(cat "$1"); do
  tmp=$(mktemp /tmp/temp.XXXXXXXXXX)
  if [ -r $word.in ]; then
    if [ ! -r $word.args ]; then
      $2 < $word.in > $tmp
    else
      $2 $(cat $word.args) < $word.in > $tmp
    fi
  else
    if [ ! -r $word.args ]; then
      exit 1
    fi

    $2 $(cat $word.args) > $tmp
  fi

  diff $word.out $tmp > /dev/null
  if [ $? -ne 0 ]; then
    echo "Test failed:" $word
    echo "Args:"
    if [ -r $word.args ]; then
        cat $word.args
    fi
    echo "Input:"
    if [ -r $word.in ]; then
        cat $word.in
    fi
    echo "Expected:"
    cat $word.out
    echo "Actual:"
    cat $tmp
  fi
  rm $tmp
done

